### PR TITLE
Bundle Update on 2016-01-28

### PR DESCRIPTION
**Pull request by deppbot**
**Updated RubyGems:**

- Updated: [rspec-core](http://github.com/rspec/rspec-core), [3.4.1...3.4.2](https://github.com/rspec/rspec-core/compare/v3.4.1...v3.4.2) ([CHANGELOG](https://github.com/rspec/rspec-core/blob/master/Changelog.md))

--

Brought to you by [deppbot](https://www.deppbot.com) - Automated Dependency Updates

<sub>Feedback or Bug Reports? Please let us know via [Email](mailto:ask@deppbot.com) or [GitHub Issues](https://github.com/deppbot/feedback).</sub>

### CODE REVIEW

**Comment by davetron5000** [comment]
@simeonwillbanks @webdestroya @codevelvet @jimbert My instinct is to merge this and not do a release.

I *think* the way to consider these auto-updates (if we keep doing them) is:

* if it just changes `Gemfile.lock` and won't change the deps of the gem, merge when green
* if it **does** change the gem's runtime or development dependencies, we **do** make a new release (a bugfix one?)

Does that sound right?

**Comment by jimbert** [comment]
makes sense to me

**Comment by simeonwillbanks** [comment]
@davetron5000 This Pull Request [changes a development dependency](https://github.com/stitchfix/immutable-struct/blob/bb79ebfb7df1b853b74bee0fff539b31d67b3cec/immutable-struct.gemspec#L23), so we would merge and release?

**Comment by davetron5000** [comment]
It doesn't actually change the version this gem depends on.  It just forces us to run tests against the latest version of rspec (in this case).  `Gemfile.lock` isn't included in the `.gem` and doesn't affect how bundler perceives the dependencies.  The way the gemspec is written, this gem should work with *any* version of RSpec.  That's probably wrong, but this PR doesn't change that.

**Comment by simeonwillbanks** [comment]
> if it does change the gem's runtime or development dependencies

This gem doesn't specifiy a version, so we don't release.  If the gem specified a version, we'd release.  :+1: 

@davetron5000 Now I understand.  Thanks!

**Comment by davetron5000** [comment]
It's slightly more subtle.  Suppose our gemspec had

```ruby
s.add_development_dependency 'rspec', '~> 3.0'
```

And suppose deppbot bumped the Gemfile.lock from `3.1.4` to `3.1.5`.  That doesn't change the version of rspec this gem depends on, just the one we're building against, so we wouldn't release.

**Comment by simeonwillbanks** [comment]
:cool: :sunglasses:

**Pull request merged**
